# Generated by Django 5.1.2 on 2024-10-25 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='remaining_quantity',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='api.order'),
        ),
    ]
