# Generated by Django 5.1.2 on 2024-10-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_remaining_quantity_alter_qrcode_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
