# Generated by Django 5.1.2 on 2024-10-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_qrcode_attendee_name_alter_qrcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='api.order'),
        ),
    ]
