# Generated by Django 5.1.2 on 2024-11-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_qrcode_attendee_name_alter_qrcode_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
