# Generated by Django 5.1.2 on 2024-11-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_amount',
            new_name='price',
        ),
    ]
