# Generated by Django 5.1.2 on 2024-10-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
