# Generated by Django 5.1.2 on 2024-10-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_order_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_phone_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='template_type',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
